# Services
services:
  # Apache + PHP
  apache_php:
    image: php:8.3-apache
  # Preparamos un volumen para almacenar nuestro código
    volumes:
      - ./:/var/www/html
      #- ./.docker/apache:/etc/apache2/sites-available
    expose:
      - 80
    ports:
      - 8080:80